spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: app_rw
    password: app_rw

logging:
  level:
    web: INFO
    org.springframework.web.servlet: INFO
    org.springframework.jdbc: INFO
    Exposed: INFO
    com.example.demo: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
